apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncall-api
  namespace: hypertheory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oncall-api
  template:
    metadata:
      labels:
        app: oncall-api
    spec:
      containers:
      - name: oncall-api
        image: oncall-api:v1.0
        volumeMounts:
          - mountPath: /app/Data/
            name: schedule-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz/live
            port: 80
            scheme: HTTP
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 5
          httpGet: 
            path: /healthz/ready
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        startupProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz/startup
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          
      volumes:
        - name: schedule-config
          configMap:
            name: schedule-config-map


