apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncall-api
  namespace: hypertheory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oncall-api
  template:
    metadata:
      labels:
        app: oncall-api
    spec:
      containers:
      - name: oncall-api
        image: oncall-api:v1.0
        volumeMounts:
          - mountPath: /app/Data/
            name: schedule-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      volumes:
        - name: schedule-config
          configMap:
            name: schedule-config-map


